---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace : development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: modem7/docker-rickroll
        ports:
        - containerPort: 8080

